#!/bin/bash

### SAVE CURRENT DIRECTORY ###
CURRENT_DIR=$(pwd)

### TOP DIRECTORY ###
DIR_FILE=$(dirname "${BASH_SOURCE}")
cd $DIR_FILE
export TOP=$(pwd)
### VERILATOR BINARY PATH ###
export VERILATOR_ROOT=/opt/verilator

### VERILATOR BINARY PATH ###
VERILATOR_BIN_PATH=$VERILATOR_ROOT/bin
if [[ $PATH != *$VERILATOR_BIN_PATH* ]]; then
  export PATH=$PATH:$VERILATOR_BIN_PATH
fi

echo "TOP=$TOP"
echo "VERILATOR_ROOT=$VERILATOR_ROOT"

cd $CURRENT_DIR
